language: python
dist: focal
python:
  - "3.10"

install:
  - python3 -m pip install --upgrade pip
  - python3 -m install python-telegram-bot --upgrade

script:
  - travis_wait 30 mvn install
  - chmod +x *
  - travis_wait 120 python3 rex.py
